---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloudflare.cloudflare.unmango.net
  resources:
  - cloudflareddeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.unmango.net
  resources:
  - cloudflareddeployments/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.unmango.net
  resources:
  - cloudflareddeployments/status
  verbs:
  - get
  - patch
  - update
